[project]
name = "autogen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat[gemini,lmm,retrievechat]~=0.2",
    "autogen-ext[azure,ollama,openai]>=0.7.5",
    "autogenstudio>=0.0.49",
    "azure-ai-inference>=1.0.0b9",
    "dotenv>=0.9.9",
    "ipykernel>=7.2.0",
    "langchain-huggingface>=1.2.2",
    "litellm[proxy]>=1.87.0",
    "node>=2.0.0",
    "npx>=0.1.8",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "playwright>=1.60.0",
    "pyautogen[ollama]>=0.10.0",
]
